name: "My survey"
token: "hello"
secret: "presenterSecret"
survey:
  - type: "text"
    question: "Describe your experience with GoLang."
    result: "wordcloud"
  - type: "multiple"
    question: "What is your role?"
    answers:
      - "Junior"
      - "Senior"
      - "Elite"
    result: "bar"
  - type: "multiple"
    question: "Which programming languages do you use?"
    answers:
      - "Go"
      - "Python"
      - "JavaScript"
    result: "bar"
  - type: "radio"
    question: "Are you a morning person?"
    answers:
      - "yes"
      - "no"
      - "coffee"
    result: "bar"
