apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  selector:
    app: {{ .Release.Name }}-api
  {{- if .Values.service }}
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- end }}