replicaCount: 1
image:
  repository: ${REGISTRY}/${IMAGE_NAME}
  tag: ${IMAGE_TAG}
  digest: ${IMAGE_DIGEST}
  pullPolicy: IfNotPresent
env:
  TZ: "Europe/Oslo"
ingress:
  enabled: false
  hostname: example.com
securityContext:
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 100
